[images]
  remote_images = [
    "https://image\\.tmdb\\.org/t/p/.*",
    "https://via\\.placeholder\\.com/.*"
  ]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
